/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetox.view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetox.Class.Carro;
import projetox.Class.Cliente;
import projetox.Class.Venda;
import projetox.controller.Controller_Venda;

/**
 *
 * @author Luan Paulo
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarVenda
     */
    
    DefaultTableModel modeloLocacao = new DefaultTableModel();
    Controller_Venda validar = new Controller_Venda();
    ArrayList<Carro> carros = new ArrayList<>();
    
    public TelaVenda() {
        initComponents();
            this.setLocationRelativeTo(null);

        DateFormat Formatodata = new SimpleDateFormat("dd/MM/yyyy");
        Date data = new Date();
        JTextData.setText(Formatodata.format(data));
        jTable1.setModel(modeloLocacao);
        Date banco = new Date();

        modeloLocacao.setColumnIdentifiers(new String[]{"Nome", "Codigo", "Tipo", "valor"});

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBtnFinalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTextDevolucao = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        JBtnRemover = new javax.swing.JButton();
        JTextData = new javax.swing.JLabel();
        jPanelCliente = new javax.swing.JPanel();
        jMatricula = new javax.swing.JLabel();
        jNomeCliente = new javax.swing.JLabel();
        JTextNome = new javax.swing.JTextField();
        jBPesquisarCliente = new javax.swing.JButton();
        CPF = new javax.swing.JLabel();
        JTextCodigo = new javax.swing.JLabel();
        jPanelFilme1 = new javax.swing.JPanel();
        jNomeFil1 = new javax.swing.JLabel();
        JTextModelo = new javax.swing.JTextField();
        jBPesquisarCarro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Valor = new javax.swing.JLabel();
        jValorTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda de Veículo");

        JBtnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/Próximo.png"))); // NOI18N
        JBtnFinalizar.setText("Finalizar");
        JBtnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnFinalizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Data de Locação :");

        jLabel3.setText("Data de Devolução :");

        JBtnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/delete.png"))); // NOI18N
        JBtnRemover.setText("Remover"); // NOI18N
        JBtnRemover.setToolTipText("");
        JBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnRemoverActionPerformed(evt);
            }
        });

        JTextData.setText("Data");

        jPanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jMatricula.setText("CPF:");

        jNomeCliente.setText("Nome:");

        JTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNomeActionPerformed(evt);
            }
        });

        jBPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/search.png"))); // NOI18N
        jBPesquisarCliente.setText("Pesquisar");
        jBPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarClienteActionPerformed(evt);
            }
        });

        JTextCodigo.setText("           ");

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(CPF))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextCodigo)))
                .addGap(72, 72, 72)
                .addComponent(jNomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisarCliente)
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jMatricula)
                .addComponent(jBPesquisarCliente)
                .addComponent(jNomeCliente)
                .addComponent(JTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CPF)
                .addComponent(JTextCodigo))
        );

        jPanelFilme1.setBorder(javax.swing.BorderFactory.createTitledBorder("Carro"));

        jNomeFil1.setText("Modelo:");

        jBPesquisarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/search.png"))); // NOI18N
        jBPesquisarCarro.setText("Pesquisar");
        jBPesquisarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarCarroActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("tabela"); // NOI18N
        jTable1.setOpaque(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelFilme1Layout = new javax.swing.GroupLayout(jPanelFilme1);
        jPanelFilme1.setLayout(jPanelFilme1Layout);
        jPanelFilme1Layout.setHorizontalGroup(
            jPanelFilme1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilme1Layout.createSequentialGroup()
                .addGroup(jPanelFilme1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilme1Layout.createSequentialGroup()
                        .addComponent(jNomeFil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPesquisarCarro))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanelFilme1Layout.setVerticalGroup(
            jPanelFilme1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilme1Layout.createSequentialGroup()
                .addGroup(jPanelFilme1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomeFil1)
                    .addComponent(JTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarCarro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Valor.setText(" ");
        Valor.setMaximumSize(new java.awt.Dimension(0, 4));
        Valor.setMinimumSize(new java.awt.Dimension(0, 4));
        Valor.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Valor, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jValorTotal.setText("Valor Total R$");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/Logo Menor.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelFilme1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextData)
                            .addComponent(JTextDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(309, 309, 309)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JBtnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnRemover))
                        .addGap(17, 17, 17)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFilme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(JTextData))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jValorTotal, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JTextDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JBtnRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnFinalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnFinalizarActionPerformed
        Venda venda = new Venda();
        ArrayList<Carro> fi = new ArrayList<>();
        Cliente cli = new Cliente();
        if (!"".equals(JTextCodigo.getText())) {
            try {
                cli.setId(Integer.parseInt(JTextCodigo.getText()));
                venda.setCliente(cli);
            } catch (Exception e) {
                cli.setId(0);
                venda.setCliente(cli);
            }
        }
        {
               if (!"".equals(Valor.getText())) {
                try {
                    venda.setPreco(Double.parseDouble(Valor.getText()));
                } catch (Exception e) {
                    venda.setPreco(0);
                }
            }
            venda.setData(JTextData.getText());
            if (modeloLocacao.getRowCount() > 0) {
                for (int i = 0; i < carros.size(); i++) {
                    Carro f = new Carro();
                    f.setId(carros.get(i).getId());
                    fi.add(f);
                }
            }
            venda.setCarro(fi);
            try {
                validar.validarLocacao(venda);
                JOptionPane.showMessageDialog(JTextNome, "Locação Concluida");
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(JTextNome, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_JBtnFinalizarActionPerformed

    private void JBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRemoverActionPerformed
            if (jTable1.getRowCount() > 0) {
            double a = Double.parseDouble(Valor.getText());
            String V = String.valueOf(carros.get(jTable1.getSelectedRow()).getId());//.substring(0, 4);
            a = a - Double.parseDouble(V);
            modeloLocacao.removeRow(jTable1.getSelectedRow());
            Valor.setText(String.valueOf(a).substring(0, 4));
            JOptionPane.showMessageDialog(JTextNome, "Filme Removido da lista");
            int index = jTable1.getSelectedRowCount();
            carros.remove(index);

        } else {
            JOptionPane.showMessageDialog(JTextNome, "Selecione o Filme a ser Retirado");
        }
    }//GEN-LAST:event_JBtnRemoverActionPerformed

    private void JTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNomeActionPerformed

    }//GEN-LAST:event_JTextNomeActionPerformed

    private void jBPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarClienteActionPerformed
       String nome = JTextNome.getText();
        TelaConsultaCliente c = new TelaConsultaCliente(nome, JTextNome, JTextCodigo);
        c.show();
    }//GEN-LAST:event_jBPesquisarClienteActionPerformed

    private void jBPesquisarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarCarroActionPerformed
                    TelaConsultaCarro c = new TelaConsultaCarro(JTextModelo.getText(), modeloLocacao, Valor, carros);
                     c.show();
    }//GEN-LAST:event_jBPesquisarCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JButton JBtnFinalizar;
    private javax.swing.JButton JBtnRemover;
    private javax.swing.JLabel JTextCodigo;
    private javax.swing.JLabel JTextData;
    private com.toedter.calendar.JDateChooser JTextDevolucao;
    private javax.swing.JTextField JTextModelo;
    private javax.swing.JTextField JTextNome;
    private javax.swing.JLabel Valor;
    private javax.swing.JButton jBPesquisarCarro;
    private javax.swing.JButton jBPesquisarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMatricula;
    private javax.swing.JLabel jNomeCliente;
    private javax.swing.JLabel jNomeFil1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelFilme1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jValorTotal;
    // End of variables declaration//GEN-END:variables
}
