/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetox.view;

import javax.swing.JOptionPane;
import projetox.Class.Funcionario;

/**
 *
 * @author Luan Paulo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    int index = 0;
    
    public TelaPrincipal(Funcionario funcionario) {
        index = funcionario.getId();
        initComponents();
        this.setLocationRelativeTo(null);
        if (funcionario.getCargo().equals("Funcionario")) {
            JCadFuncionario.setVisible(false);
            JFolha.setVisible(false);
            jVariaveis.setVisible(false);
           
        }else if(funcionario.getCargo().equals("Comissionado")) {
            JCadFuncionario.setVisible(false);
            JCadCarro.setVisible(false);
            JFolha.setVisible(false);
            jVariaveis.setVisible(false);
            JEstoque.setVisible(false);
                     
        }
        JOptionPane.showMessageDialog(null, "olá "+funcionario.getNome()+"\nAcesso:"+funcionario.getCargo()+"\nSeja Bem-Vindo ao Sistema","Bem Vindo", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JMenu = new javax.swing.JMenuBar();
        JCadastrar = new javax.swing.JMenu();
        JCadCarro = new javax.swing.JMenuItem();
        JCadCliente = new javax.swing.JMenuItem();
        JCadFuncionario = new javax.swing.JMenuItem();
        JOperacao = new javax.swing.JMenu();
        JOpeAluguel = new javax.swing.JMenuItem();
        JOpeVendas = new javax.swing.JMenuItem();
        JEstoque = new javax.swing.JMenu();
        JFolha = new javax.swing.JMenu();
        jVariaveis = new javax.swing.JMenu();
        JSair = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema ProjetoX - Locação e Venda de Carros");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/Logo Menor.png"))); // NOI18N

        JCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/gear.png"))); // NOI18N
        JCadastrar.setText("Gerenciar");

        JCadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/car.png"))); // NOI18N
        JCadCarro.setText("Carro");
        JCadCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCadCarroMouseClicked(evt);
            }
        });
        JCadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCadCarroActionPerformed(evt);
            }
        });
        JCadastrar.add(JCadCarro);

        JCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/Cliente.png"))); // NOI18N
        JCadCliente.setText("Cliente");
        JCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCadClienteActionPerformed(evt);
            }
        });
        JCadastrar.add(JCadCliente);

        JCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/Funcionario.png"))); // NOI18N
        JCadFuncionario.setText("Funcionário");
        JCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCadFuncionarioActionPerformed(evt);
            }
        });
        JCadastrar.add(JCadFuncionario);

        JMenu.add(JCadastrar);

        JOperacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/money.png"))); // NOI18N
        JOperacao.setText("Operação");

        JOpeAluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/Alugar.png"))); // NOI18N
        JOpeAluguel.setText("Aluguel...");
        JOpeAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOpeAluguelActionPerformed(evt);
            }
        });
        JOperacao.add(JOpeAluguel);

        JOpeVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/Venda.png"))); // NOI18N
        JOpeVendas.setText("Vendas...");
        JOpeVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOpeVendasActionPerformed(evt);
            }
        });
        JOperacao.add(JOpeVendas);

        JMenu.add(JOperacao);

        JEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/warehouse.png"))); // NOI18N
        JEstoque.setText("Estoque");
        JEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JEstoqueMouseClicked(evt);
            }
        });
        JEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEstoqueActionPerformed(evt);
            }
        });
        JMenu.add(JEstoque);

        JFolha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/bank.png"))); // NOI18N
        JFolha.setText("Folha de Pagamento");
        JFolha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JFolhaMouseClicked(evt);
            }
        });
        JFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFolhaActionPerformed(evt);
            }
        });
        JMenu.add(JFolha);

        jVariaveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/browser.png"))); // NOI18N
        jVariaveis.setText("Variaveis");
        jVariaveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVariaveisMouseClicked(evt);
            }
        });
        JMenu.add(jVariaveis);

        JSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetox/view/Imagens/logout.png"))); // NOI18N
        JSair.setText("Sair");
        JSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSairMouseClicked(evt);
            }
        });
        JSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSairActionPerformed(evt);
            }
        });
        JMenu.add(JSair);

        setJMenuBar(JMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel2)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JCadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCadCarroActionPerformed
            //chamar tela Listar Carro
            TelaGerenciarCarro GCarro = new TelaGerenciarCarro();
            GCarro.show();
    }//GEN-LAST:event_JCadCarroActionPerformed

    private void JCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCadClienteActionPerformed
           //chamar tela Listar Cliente
           TelaGerenciarCliente GCliente = new TelaGerenciarCliente();
            GCliente.show();
    }//GEN-LAST:event_JCadClienteActionPerformed

    private void JCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCadFuncionarioActionPerformed
           //chamar tela Listar Funcionario
           TelaGerenciarFuncionario GFunc = new TelaGerenciarFuncionario();
           GFunc.show();
    }//GEN-LAST:event_JCadFuncionarioActionPerformed

    private void JOpeAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOpeAluguelActionPerformed
            //chamar tela Listar Aluguel
            TelaGerenciarAluguel GAlug = new TelaGerenciarAluguel();
            GAlug.show();
            
    }//GEN-LAST:event_JOpeAluguelActionPerformed

    private void JOpeVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOpeVendasActionPerformed
         //chamar tela Listar Vendas
         TelaGerenciarVenda GVend = new TelaGerenciarVenda();
         GVend.show();
    }//GEN-LAST:event_JOpeVendasActionPerformed

    private void JEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEstoqueActionPerformed
        //chamar tela Gerenciar Estoque
        //evento morto
    }//GEN-LAST:event_JEstoqueActionPerformed

    private void JFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFolhaActionPerformed
        //chamar tela Gerenciar Folha
        //evento morto
    }//GEN-LAST:event_JFolhaActionPerformed

    private void JSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSairActionPerformed

    }//GEN-LAST:event_JSairActionPerformed

    private void JSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSairMouseClicked
        Runtime.getRuntime().exit(0); 
        TelaLogin tl = new  TelaLogin();
        tl.show();
        
    }//GEN-LAST:event_JSairMouseClicked

    private void JCadCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCadCarroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JCadCarroMouseClicked

    private void JEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JEstoqueMouseClicked
        // TODO add your handling code here:
            TelaGerenciarEstoque GEst = new TelaGerenciarEstoque();
            GEst.show();


    }//GEN-LAST:event_JEstoqueMouseClicked

    private void JFolhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JFolhaMouseClicked
        // TODO add your handling code here:
        TelaGerenciarFolhaPagamento GFolha = new TelaGerenciarFolhaPagamento();
        GFolha.show();
    }//GEN-LAST:event_JFolhaMouseClicked

    private void jVariaveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVariaveisMouseClicked
        // TODO add your handling code here:
        TelaGerenciarVariaveisSistema TGV = new TelaGerenciarVariaveisSistema();
        TGV.show();
    }//GEN-LAST:event_jVariaveisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JCadCarro;
    private javax.swing.JMenuItem JCadCliente;
    private javax.swing.JMenuItem JCadFuncionario;
    private javax.swing.JMenu JCadastrar;
    private javax.swing.JMenu JEstoque;
    private javax.swing.JMenu JFolha;
    private javax.swing.JMenuBar JMenu;
    private javax.swing.JMenuItem JOpeAluguel;
    private javax.swing.JMenuItem JOpeVendas;
    private javax.swing.JMenu JOperacao;
    private javax.swing.JMenu JSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jVariaveis;
    // End of variables declaration//GEN-END:variables
}
